{
  if (cause instanceof OUserException)   return (OException)cause;
  exception.initCause(cause);
  return exception;
}
